# Output sample rate
data_fs: 44100

# Input sample rate
lp_fs: 16000


# Length of each training sample
training_length: 1

# When processing a whole audio file, split it into segments to process one at
# a time, for memory reasons. This is the length in seconds of each segment.
# This number will change depending on the system.
eval_segment_seconds: 15

# Where to save results
saved_model_folder: 'models/'
results_folder: 'result_files/'
samples_folder: 'samples/'


# Spectrogram discriminator list, w/ different window sizes
spectrogram_win_lens: [2048]
spectrogram_hop_divider: 4


# Inclusive ranges for parameters
filters:
  cutoff_low: 7700
  cutoff_high: 8000
  butterworth:
    order_low: 40
    order_high: 60
  bessel:
    order_low: 5
    order_high: 15
  chebyshev:
    order_low: 10
    order_high: 20
    rp: 0.1
  elliptic:
    order_low: 8
    order_high: 15
    rp: 0.01
    rs_low: 80
    rs_high: 120

# Tested, found ideal values
#filters:
#  cutoff: 5000
#  butterworth:
#    order: 50
#  bessel:
#    order: 10
#  chebyshev:
#    order: 12
#    rp: 0.1
#  elliptic:
#    order: 12
#    rp: 0.01
#    rs: 100
